version: "3.7"

services:
  build-container:
    container_name: fabric_starter_builder_container
    image: kilpio/fabric-starter-builder-container:latest
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GRADLE_UID=${GRADLE_UID:-$UID}
      - DOCKER_GID=${DOCKER_GID}